<?= $this->extend('layouts/main') ?>

<?= $this->section('content') ?>
<div class="card p-4">
    <div class="d-flex justify-content-between align-items-center mb-4">
        <div>
            <h5 class="mb-1">Generated Reports</h5>
            <p class="text-muted small mb-0">View and download all generated research reports.</p>
        </div>
    </div>

    <div class="table-responsive">
        <table class="table table-hover align-middle">
            <thead>
                <tr>
                    <th>Report Name</th>
                    <th>Type</th>
                    <th>Date Generated</th>
                    <th>Generated By</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td colspan="5" class="text-center py-5 text-muted">
                        <i class="bi bi-file-earmark-bar-graph fs-1 d-block mb-3"></i>
                        No reports generated yet.
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
</div>
<?= $this->endSection() ?>
